### ISSUE TITLE
태그 제외 및 검색 관련 기능 향상

### ISSUE THREAD

**Issue by SeaniaTwix** [Ploenar/dummy#1]
## 검색어 제외
몇 개의 플래그를 지정해 태그 제외가 가능하였으면 합니다. 예를 들어 _!학생_을 검색한다면 학생 태그가 포함된 모든 게시물을 검색 결과에서 보여주지 않는다던가 말이죠.

## 검색 기능 향상
태그 자동 완성이 있으면 합니다.

**Comment by Ploenar** [comment]
하긴 어느정도 급한 내용이긴 하네요. 해야할 우선순위 높여두겠습니다.

**Comment by Ploenar** [comment]
일단 제가 생각하는 두 항목에 대한 의견은 이렇습니다

## 검색어 제외
이부분의 경우엔 맘에 안드는 항목을 제외할수 있으니 반드시 추가를 해야한다고 생각합니다. 일단 이건 다음 업데이트에 바로 추가할 예정이니 기다려주시기 바랍니다.

## 검색 기능 향상
태그 자동 완성 기능의 경우, 이전에 시도한적이 있었지만 코드가 너무 엉켜있어서 작성에 실패했었습니다. 아마 코드 정리가 어느정도 끝난 베타버전에나 추가가 가능할것 같네요.
